import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'
import LanguageSwitcher from './langSwitcher'
import { TPropsLayout } from './types'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'

const font = Nunito({
  subsets: ['cyrillic'],
  variable: '--font-nunito',
  weight: ['400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout(props: TPropsLayout) {
  const {
    children,
    params: { lang },
  } = props
  const messages = await getMessages()

  return (
    <html lang={lang}>
      <NextIntlClientProvider messages={messages}>
        <body className={`${font.variable} antialiased`}>
          <main className='min-h-screen'>
            <LanguageSwitcher lang={lang} />
            {children}
          </main>
        </body>
      </NextIntlClientProvider>
    </html>
  )
}
